### ISSUE TITLE
Assign to someone doesnt work

### ISSUE THREAD

**Issue by pittersnider** [danshumaker/jira-cli#10]
It says Issue X assigned to undefined.
I tried all possible values in [user] (name, name.lastname, email, etc)

**Comment by danshumaker** [comment]
Hi @pittersnider ,  It looks like they've changed the back-end a little.  They say that { "name" : "dshumaker" } is a valid payload but what I get from the api is this message:

> {
    "errorMessages": [
        "'accountId' must be the only user identifying query parameter in GDPR strict mode."
    ],
    "errors": {}
}

However, when I change to use the accountId it does work.  The problem with that is you only know your own (or any user's) account id by submitting another query.    The account ids are pretty nasty

557058:fefa7ec7-ba34-4d29-bfeb-99999999   for example.

You can find the assignable users via https://docs.atlassian.com/software/jira/docs/api/REST/8.1.0/#api/2/user-findAssignableUsers

I'll have to put in some other options to help the users determine what values to assign a ticket with.  I'd love to find a way that allows human readible names rather than the accountId's.

**Comment by danshumaker** [comment]
@pittersnider  Try the latest version 1.3.0 .  Once you get your accountId you can supply that on the command line and it should work.  Let me know. thx.
