### ISSUE TITLE
Q: different new vs create

### ISSUE THREAD

**Issue by mikhaili** [danshumaker/jira-cli#17]
Hey what the different new vs create?

**Comment by danshumaker** [comment]
The difference is mainly in different authors.  This project was forked from several other projects.  Idealily I'd like to consolidate new and create because they seem redundant. I just havn't had time. I believe create had more templating options than new does.  When I diff the two source files new.js and create.js they are very different.   As with all "features" the more complex they are the more issues they tend to have, so before I just through out one of them (in favor of the other), I'd like to make sure we keep the essentials of creating a jira ticket.   Jira Ticket templates was a very nice concept in my opinion but in actual usage, people just used the simpler "new" if I recall.   However since 99% of the people are so use to creating jira tickets in the browser, I got VERY little feedback on what people actually wanted and used.

Thus I appreciate your questions and feedback @mikhaili !!!

**Comment by mikhaili** [comment]
do u use create or new 
do u use params with create / new command
