### ISSUE TITLE
"npm WARN" deprecated dependencies identified when installing

### ISSUE THREAD

**Issue by bcdady** [danshumaker/jira-cli#56]
Repro steps:
1. open a zsh terminal application on MacOS, running node v14.15.4 and npm v7.19.0 (other versions of node and npm may also work)
2. run: `npm install -g jira-cli`
3. See the following "WARN" messages:

```shell
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 194 packages, and audited 195 packages in 6s

24 packages are looking for funding
  run `npm fund` for details

4 low severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

**Comment by bcdady** [comment]
After running `npm audit fix`, npm confirmed `found 0 vulnerabilities`.

**Comment by danshumaker** [comment]
Thanks for the issue, however `npm audit fix` did not exit cleanly for me.  I've updated the repo anyway.  New version 2.7.0.
YMMV.
After the `npm audit fix` there was issues with underscore, that suggested a run of `npm audit --force`. So that's what was run.  However even after that there are still two vulnerabilities.

```
# npm audit report

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution - https://npmjs.com/advisories/1674
No fix available
node_modules/testr/node_modules/underscore
  testr  *
  Depends on vulnerable versions of underscore
  node_modules/testr

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```

Ref: https://github.com/danshumaker/jira-cli/releases/tag/v2.7.0
