### ISSUE TITLE
jira done ISSUE -r Done switch does not work

### ISSUE THREAD

**Issue by O5ten** [danshumaker/jira-cli#8]
**when i run**

`jira done JIRA-123 -r Done`

**then i expect**

> Resolution status to be Done. 

But it does not. 

**workaround**

edit `~/jira-cli/config.json` to have `"check_resolution": true`
```json
    "jira_done": {
      "status": "Done",
      "check_resolution": true
    }
```

**Comment by danshumaker** [comment]
@O5ten One option i've been using lately is the "mark" command.  The mark command has a prompt that shows you which valid status' a ticket can be assigned to. You then type in the number value and the transition is done.  Otherwise, if you were to use the done or review commands you have to ensure that your config.json file is setup correctly to match your jira instance.  Some projects change the definition of done so that "done" on one project might transition the ticket to "review" status.  An unfortunate by product of jira being flexible.    Marking as closed.
